// <auto-generated />
using Bible2PPT.Services.BibleIndexService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bible2PPT.Services.BibleIndexService.Migrations
{
    [DbContext(typeof(BibleIndexContext))]
    partial class BibleIndexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Bible2PPT.Services.BibleIndexService.BookInfo", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key", "Kind", "LanguageCode", "Version");

                    b.ToTable("BookInfos");

                    b.HasData(
                        new
                        {
                            Key = 1,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "창세기"
                        },
                        new
                        {
                            Key = 1,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "창"
                        },
                        new
                        {
                            Key = 2,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "출애굽기"
                        },
                        new
                        {
                            Key = 2,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "출"
                        },
                        new
                        {
                            Key = 3,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "레위기"
                        },
                        new
                        {
                            Key = 3,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "레"
                        },
                        new
                        {
                            Key = 4,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "민수기"
                        },
                        new
                        {
                            Key = 4,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "민"
                        },
                        new
                        {
                            Key = 5,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "신명기"
                        },
                        new
                        {
                            Key = 5,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "신"
                        },
                        new
                        {
                            Key = 6,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "여호수아"
                        },
                        new
                        {
                            Key = 6,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "수"
                        },
                        new
                        {
                            Key = 7,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "사사기"
                        },
                        new
                        {
                            Key = 7,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "삿"
                        },
                        new
                        {
                            Key = 8,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "룻기"
                        },
                        new
                        {
                            Key = 8,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "룻"
                        },
                        new
                        {
                            Key = 9,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "사무엘상"
                        },
                        new
                        {
                            Key = 9,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "삼상"
                        },
                        new
                        {
                            Key = 10,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "사무엘하"
                        },
                        new
                        {
                            Key = 10,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "삼하"
                        },
                        new
                        {
                            Key = 11,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "열왕기상"
                        },
                        new
                        {
                            Key = 11,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "왕상"
                        },
                        new
                        {
                            Key = 12,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "열왕기하"
                        },
                        new
                        {
                            Key = 12,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "왕하"
                        },
                        new
                        {
                            Key = 13,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "역대상"
                        },
                        new
                        {
                            Key = 13,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "대상"
                        },
                        new
                        {
                            Key = 14,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "역대하"
                        },
                        new
                        {
                            Key = 14,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "대하"
                        },
                        new
                        {
                            Key = 15,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "에스라"
                        },
                        new
                        {
                            Key = 15,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "스"
                        },
                        new
                        {
                            Key = 16,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "느헤미야"
                        },
                        new
                        {
                            Key = 16,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "느"
                        },
                        new
                        {
                            Key = 17,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "에스더"
                        },
                        new
                        {
                            Key = 17,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "에"
                        },
                        new
                        {
                            Key = 18,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "욥기"
                        },
                        new
                        {
                            Key = 18,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "욥"
                        },
                        new
                        {
                            Key = 19,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "시편"
                        },
                        new
                        {
                            Key = 19,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "시"
                        },
                        new
                        {
                            Key = 20,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "잠언"
                        },
                        new
                        {
                            Key = 20,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "잠"
                        },
                        new
                        {
                            Key = 21,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "전도서"
                        },
                        new
                        {
                            Key = 21,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "전"
                        },
                        new
                        {
                            Key = 22,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "아가"
                        },
                        new
                        {
                            Key = 22,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "아"
                        },
                        new
                        {
                            Key = 23,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "이사야"
                        },
                        new
                        {
                            Key = 23,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "사"
                        },
                        new
                        {
                            Key = 24,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "예레미야"
                        },
                        new
                        {
                            Key = 24,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "렘"
                        },
                        new
                        {
                            Key = 25,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "예레미야애가"
                        },
                        new
                        {
                            Key = 25,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "애"
                        },
                        new
                        {
                            Key = 26,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "에스겔"
                        },
                        new
                        {
                            Key = 26,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "겔"
                        },
                        new
                        {
                            Key = 27,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "다니엘"
                        },
                        new
                        {
                            Key = 27,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "단"
                        },
                        new
                        {
                            Key = 28,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "호세아"
                        },
                        new
                        {
                            Key = 28,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "호"
                        },
                        new
                        {
                            Key = 29,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요엘"
                        },
                        new
                        {
                            Key = 29,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "욜"
                        },
                        new
                        {
                            Key = 30,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "아모스"
                        },
                        new
                        {
                            Key = 30,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "암"
                        },
                        new
                        {
                            Key = 31,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "오바댜"
                        },
                        new
                        {
                            Key = 31,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "옵"
                        },
                        new
                        {
                            Key = 32,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요나"
                        },
                        new
                        {
                            Key = 32,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "욘"
                        },
                        new
                        {
                            Key = 33,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "미가"
                        },
                        new
                        {
                            Key = 33,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "미"
                        },
                        new
                        {
                            Key = 34,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "나홈"
                        },
                        new
                        {
                            Key = 34,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "나"
                        },
                        new
                        {
                            Key = 35,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "하박국"
                        },
                        new
                        {
                            Key = 35,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "합"
                        },
                        new
                        {
                            Key = 36,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "스바냐"
                        },
                        new
                        {
                            Key = 36,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "습"
                        },
                        new
                        {
                            Key = 37,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "학개"
                        },
                        new
                        {
                            Key = 37,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "학"
                        },
                        new
                        {
                            Key = 38,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "스가랴"
                        },
                        new
                        {
                            Key = 38,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "슥"
                        },
                        new
                        {
                            Key = 39,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "말라기"
                        },
                        new
                        {
                            Key = 39,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "말"
                        },
                        new
                        {
                            Key = 55,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "마태복음"
                        },
                        new
                        {
                            Key = 55,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "마"
                        },
                        new
                        {
                            Key = 56,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "마가복음"
                        },
                        new
                        {
                            Key = 56,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "막"
                        },
                        new
                        {
                            Key = 57,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "누가복음"
                        },
                        new
                        {
                            Key = 57,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "눅"
                        },
                        new
                        {
                            Key = 58,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요한복음"
                        },
                        new
                        {
                            Key = 58,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요"
                        },
                        new
                        {
                            Key = 59,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "사도행전"
                        },
                        new
                        {
                            Key = 59,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "행"
                        },
                        new
                        {
                            Key = 60,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "로마서"
                        },
                        new
                        {
                            Key = 60,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "롬"
                        },
                        new
                        {
                            Key = 61,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "고린도전서"
                        },
                        new
                        {
                            Key = 61,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "고전"
                        },
                        new
                        {
                            Key = 62,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "고린도후서"
                        },
                        new
                        {
                            Key = 62,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "고후"
                        },
                        new
                        {
                            Key = 63,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "갈라디아서"
                        },
                        new
                        {
                            Key = 63,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "갈"
                        },
                        new
                        {
                            Key = 64,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "에베소서"
                        },
                        new
                        {
                            Key = 64,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "엡"
                        },
                        new
                        {
                            Key = 65,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "빌립보서"
                        },
                        new
                        {
                            Key = 65,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "빌"
                        },
                        new
                        {
                            Key = 66,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "골로새서"
                        },
                        new
                        {
                            Key = 66,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "골"
                        },
                        new
                        {
                            Key = 67,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "데살로니가전서"
                        },
                        new
                        {
                            Key = 67,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "살전"
                        },
                        new
                        {
                            Key = 68,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "데살로니가후서"
                        },
                        new
                        {
                            Key = 68,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "살후"
                        },
                        new
                        {
                            Key = 69,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "디모데전서"
                        },
                        new
                        {
                            Key = 69,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "딤전"
                        },
                        new
                        {
                            Key = 70,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "디모데후서"
                        },
                        new
                        {
                            Key = 70,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "딤후"
                        },
                        new
                        {
                            Key = 71,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "디도서"
                        },
                        new
                        {
                            Key = 71,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "딛"
                        },
                        new
                        {
                            Key = 72,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "빌레몬서"
                        },
                        new
                        {
                            Key = 72,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "몬"
                        },
                        new
                        {
                            Key = 73,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "히브리서"
                        },
                        new
                        {
                            Key = 73,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "히"
                        },
                        new
                        {
                            Key = 74,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "야고보서"
                        },
                        new
                        {
                            Key = 74,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "약"
                        },
                        new
                        {
                            Key = 75,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "베드로전서"
                        },
                        new
                        {
                            Key = 75,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "벧전"
                        },
                        new
                        {
                            Key = 76,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "베드로후서"
                        },
                        new
                        {
                            Key = 76,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "벧후"
                        },
                        new
                        {
                            Key = 77,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요한일서"
                        },
                        new
                        {
                            Key = 77,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요일"
                        },
                        new
                        {
                            Key = 78,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요한이서"
                        },
                        new
                        {
                            Key = 78,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요이"
                        },
                        new
                        {
                            Key = 79,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요한삼서"
                        },
                        new
                        {
                            Key = 79,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요삼"
                        },
                        new
                        {
                            Key = 80,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "유다서"
                        },
                        new
                        {
                            Key = 80,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "유"
                        },
                        new
                        {
                            Key = 81,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "요한계시록"
                        },
                        new
                        {
                            Key = 81,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "개역 성경",
                            IsPrimary = false,
                            Value = "계"
                        },
                        new
                        {
                            Key = 1,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "창세기"
                        },
                        new
                        {
                            Key = 1,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "창"
                        },
                        new
                        {
                            Key = 2,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "출애굽기"
                        },
                        new
                        {
                            Key = 2,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "출"
                        },
                        new
                        {
                            Key = 3,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "레위기"
                        },
                        new
                        {
                            Key = 3,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "레"
                        },
                        new
                        {
                            Key = 4,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "민수기"
                        },
                        new
                        {
                            Key = 4,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "민"
                        },
                        new
                        {
                            Key = 5,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "신명기"
                        },
                        new
                        {
                            Key = 5,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "신"
                        },
                        new
                        {
                            Key = 6,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "여호수아"
                        },
                        new
                        {
                            Key = 6,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "수"
                        },
                        new
                        {
                            Key = 7,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "사사기"
                        },
                        new
                        {
                            Key = 7,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "삿"
                        },
                        new
                        {
                            Key = 8,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "룻기"
                        },
                        new
                        {
                            Key = 8,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "룻"
                        },
                        new
                        {
                            Key = 9,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "사무엘상"
                        },
                        new
                        {
                            Key = 9,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "삼상"
                        },
                        new
                        {
                            Key = 10,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "사무엘하"
                        },
                        new
                        {
                            Key = 10,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "삼하"
                        },
                        new
                        {
                            Key = 11,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "열왕기상"
                        },
                        new
                        {
                            Key = 11,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "왕상"
                        },
                        new
                        {
                            Key = 12,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "열왕기하"
                        },
                        new
                        {
                            Key = 12,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "왕하"
                        },
                        new
                        {
                            Key = 13,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "역대상"
                        },
                        new
                        {
                            Key = 13,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "대상"
                        },
                        new
                        {
                            Key = 14,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "역대하"
                        },
                        new
                        {
                            Key = 14,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "대하"
                        },
                        new
                        {
                            Key = 15,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "에스라"
                        },
                        new
                        {
                            Key = 15,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "라"
                        },
                        new
                        {
                            Key = 16,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "느헤미야"
                        },
                        new
                        {
                            Key = 16,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "느"
                        },
                        new
                        {
                            Key = 17,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "에스더"
                        },
                        new
                        {
                            Key = 17,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "더"
                        },
                        new
                        {
                            Key = 18,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "욥기"
                        },
                        new
                        {
                            Key = 18,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "욥"
                        },
                        new
                        {
                            Key = 19,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "시편"
                        },
                        new
                        {
                            Key = 19,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "시"
                        },
                        new
                        {
                            Key = 20,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "잠언"
                        },
                        new
                        {
                            Key = 20,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "잠"
                        },
                        new
                        {
                            Key = 21,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "전도서"
                        },
                        new
                        {
                            Key = 21,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "전"
                        },
                        new
                        {
                            Key = 22,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "아가"
                        },
                        new
                        {
                            Key = 22,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "아"
                        },
                        new
                        {
                            Key = 23,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "이사야"
                        },
                        new
                        {
                            Key = 23,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "사"
                        },
                        new
                        {
                            Key = 24,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "예레미야"
                        },
                        new
                        {
                            Key = 24,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "렘"
                        },
                        new
                        {
                            Key = 25,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "예레미야애가"
                        },
                        new
                        {
                            Key = 25,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "애"
                        },
                        new
                        {
                            Key = 26,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "에스겔"
                        },
                        new
                        {
                            Key = 26,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "겔"
                        },
                        new
                        {
                            Key = 27,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "다니엘"
                        },
                        new
                        {
                            Key = 27,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "단"
                        },
                        new
                        {
                            Key = 28,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "호세아"
                        },
                        new
                        {
                            Key = 28,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "호"
                        },
                        new
                        {
                            Key = 29,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요엘"
                        },
                        new
                        {
                            Key = 29,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "욜"
                        },
                        new
                        {
                            Key = 30,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "아모스"
                        },
                        new
                        {
                            Key = 30,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "암"
                        },
                        new
                        {
                            Key = 31,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "오바댜"
                        },
                        new
                        {
                            Key = 31,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "옵"
                        },
                        new
                        {
                            Key = 32,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요나"
                        },
                        new
                        {
                            Key = 32,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "욘"
                        },
                        new
                        {
                            Key = 33,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "미가"
                        },
                        new
                        {
                            Key = 33,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "미"
                        },
                        new
                        {
                            Key = 34,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "나홈"
                        },
                        new
                        {
                            Key = 34,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "나"
                        },
                        new
                        {
                            Key = 35,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "하박국"
                        },
                        new
                        {
                            Key = 35,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "합"
                        },
                        new
                        {
                            Key = 36,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "스바냐"
                        },
                        new
                        {
                            Key = 36,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "습"
                        },
                        new
                        {
                            Key = 37,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "학개"
                        },
                        new
                        {
                            Key = 37,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "학"
                        },
                        new
                        {
                            Key = 38,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "스가랴"
                        },
                        new
                        {
                            Key = 38,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "슥"
                        },
                        new
                        {
                            Key = 39,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "말라기"
                        },
                        new
                        {
                            Key = 39,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "말"
                        },
                        new
                        {
                            Key = 55,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "마태복음"
                        },
                        new
                        {
                            Key = 55,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "마"
                        },
                        new
                        {
                            Key = 56,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "마가복음"
                        },
                        new
                        {
                            Key = 56,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "막"
                        },
                        new
                        {
                            Key = 57,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "누가복음"
                        },
                        new
                        {
                            Key = 57,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "눅"
                        },
                        new
                        {
                            Key = 58,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요한복음"
                        },
                        new
                        {
                            Key = 58,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요"
                        },
                        new
                        {
                            Key = 59,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "사도행전"
                        },
                        new
                        {
                            Key = 59,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "행"
                        },
                        new
                        {
                            Key = 60,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "로마서"
                        },
                        new
                        {
                            Key = 60,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "롬"
                        },
                        new
                        {
                            Key = 61,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "고린도전서"
                        },
                        new
                        {
                            Key = 61,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "고전"
                        },
                        new
                        {
                            Key = 62,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "고린도후서"
                        },
                        new
                        {
                            Key = 62,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "고후"
                        },
                        new
                        {
                            Key = 63,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "갈라디아서"
                        },
                        new
                        {
                            Key = 63,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "갈"
                        },
                        new
                        {
                            Key = 64,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "에베소서"
                        },
                        new
                        {
                            Key = 64,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "엡"
                        },
                        new
                        {
                            Key = 65,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "빌립보서"
                        },
                        new
                        {
                            Key = 65,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "빌"
                        },
                        new
                        {
                            Key = 66,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "골로새서"
                        },
                        new
                        {
                            Key = 66,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "골"
                        },
                        new
                        {
                            Key = 67,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "데살로니가전서"
                        },
                        new
                        {
                            Key = 67,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "살전"
                        },
                        new
                        {
                            Key = 68,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "데살로니가후서"
                        },
                        new
                        {
                            Key = 68,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "살후"
                        },
                        new
                        {
                            Key = 69,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "디모데전서"
                        },
                        new
                        {
                            Key = 69,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "딤전"
                        },
                        new
                        {
                            Key = 70,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "디모데후서"
                        },
                        new
                        {
                            Key = 70,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "딤후"
                        },
                        new
                        {
                            Key = 71,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "디도서"
                        },
                        new
                        {
                            Key = 71,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "딛"
                        },
                        new
                        {
                            Key = 72,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "빌레몬서"
                        },
                        new
                        {
                            Key = 72,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "몬"
                        },
                        new
                        {
                            Key = 73,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "히브리서"
                        },
                        new
                        {
                            Key = 73,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "히"
                        },
                        new
                        {
                            Key = 74,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "야고보서"
                        },
                        new
                        {
                            Key = 74,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "약"
                        },
                        new
                        {
                            Key = 75,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "베드로전서"
                        },
                        new
                        {
                            Key = 75,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "벧전"
                        },
                        new
                        {
                            Key = 76,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "베드로후서"
                        },
                        new
                        {
                            Key = 76,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "벧후"
                        },
                        new
                        {
                            Key = 77,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요한일서"
                        },
                        new
                        {
                            Key = 77,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요일"
                        },
                        new
                        {
                            Key = 78,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요한이서"
                        },
                        new
                        {
                            Key = 78,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요이"
                        },
                        new
                        {
                            Key = 79,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요한삼서"
                        },
                        new
                        {
                            Key = 79,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요삼"
                        },
                        new
                        {
                            Key = 80,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "유다서"
                        },
                        new
                        {
                            Key = 80,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "유"
                        },
                        new
                        {
                            Key = 81,
                            Kind = 0,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "요한계시록"
                        },
                        new
                        {
                            Key = 81,
                            Kind = 1,
                            LanguageCode = "ko",
                            Version = "새번역 성경",
                            IsPrimary = false,
                            Value = "계"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
