// <auto-generated />
using System;
using Bible2PPT.Services.BuildService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bible2PPT.Services.BuildService.Migrations
{
    [DbContext(typeof(BuildContext))]
    [Migration("20220606101110_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Bible2PPT.PPT.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDestination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SplitChaptersIntoFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Bible2PPT.PPT.Job", b =>
                {
                    b.OwnsMany("Bible2PPT.Bibles.Bible", "Bibles", b1 =>
                        {
                            b1.Property<int>("Sequence")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("JobId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LanguageCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("OnlineId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("SourceId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Sequence");

                            b1.HasIndex("JobId");

                            b1.ToTable("Bible");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsOne("Bible2PPT.Services.TemplateService.Template", "Template", b1 =>
                        {
                            b1.Property<int>("JobId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BookAbbrVisible")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BookNameVisible")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ChapterNumberVisible")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("NumberOfVerseLinesPerSlide")
                                .HasColumnType("INTEGER");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Bibles");

                    b.Navigation("Template")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
