name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      # TODO: CI

      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.1.1
          branch: master
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
